### ISSUE TITLE
chance

### ISSUE THREAD

**Issue by isoz** [CubePM/MysteryBox#2]
Chance doesn't feel right, with the config below I spent 50 keys and only got the first 2 items, Golden Apples and Emerald Blocks, nothing else, am I doing something wrong?

```
      items:
          - item: "133:0:5" # emerald block
            chance: 40
          - item: "322:0:5" # golden apple
            chance: 50
          - item: "diamond_helmet:0:1:DEFAULT:protection:3:unbreaking:3"
            chance: 20
          - item: "diamond_chestplate:0:1:DEFAULT:protection:3:unbreaking:3"
            chance: 15
          - item: "diamond_leggings:0:1:DEFAULT:protection:3:unbreaking:3"
            chance: 15
          - item: "diamond_boots:0:1:DEFAULT:protection:3:unbreaking:3"
            chance: 20
          - item: "diamond_sword:0:1:DEFAULT:sharpness:2:fire_aspect:1:unbreaking:2"
            chance: 15
          - item: "diamond_pickaxe:0:1:DEFAULT:efficiency:4:unbreaking:3:fortune:2"
            chance: 40
          - item: "diamond_axe:0:1:DEFAULT:efficiency:4:unbreaking:3:fortune:2"
            chance: 40
          - item: "diamond_shovel:0:1:DEFAULT:efficiency:4:unbreaking:3:fortune:2"
            chance: 40
          - item: "diamond_hoe:0:1:DEFAULT:efficiency:4:unbreaking:3:fortune:2"
            chance: 40
          - item: "339:10:1" # 5000
            chance: 50
          - item: "339:11:1" # 10000
            chance: 30
          - item: "339:12:1" # 20000
            chance: 15
          - item: "339:20:1" # 1 vote key
            chance: 20
```

**Comment by xXNiceYT** [comment]
Than make chance 100 xd or 50

**Comment by isoz** [comment]
Now with this values I was only getting Emerald Blocks, like 9 out of 10 times.
I put the "Emerald Blocks" at the end and now I'm getting the one on top which is Golden Apples.

It seems it is prioritizing the item on top for whatever reason.

```
      items:
          - item: "322:0:5" # golden apple
            chance: 32
          - item: "diamond_helmet:0:1:none:protection:3:unbreaking:3"
            chance: 21
          - item: "diamond_chestplate:0:1:none:protection:3:unbreaking:3"
            chance: 16
          - item: "diamond_leggings:0:1:none:protection:3:unbreaking:3"
            chance: 15
          - item: "diamond_boots:0:1:none:protection:3:unbreaking:3"
            chance: 22
          - item: "diamond_sword:0:1:none:sharpness:2:fire_aspect:1:unbreaking:2"
            chance: 14
          - item: "diamond_pickaxe:0:1:none:efficiency:4:unbreaking:3:fortune:2"
            chance: 31
          - item: "diamond_axe:0:1:none:efficiency:4:unbreaking:3:fortune:2"
            chance: 32
          - item: "diamond_shovel:0:1:none:efficiency:4:unbreaking:3:fortune:2"
            chance: 33
          - item: "diamond_hoe:0:1:none:efficiency:4:unbreaking:3:fortune:2"
            chance: 34
          - item: "339:10:1:Bank Note" # 5000
            chance: 29
          - item: "339:11:1:Bank Note" # 10000
            chance: 28
          - item: "339:12:1:Bank Note" # 20000
            chance: 13
          - item: "339:20:1:Vote Key" # 1 vote key
            chance: 23
          - item: "133:0:5" # emerald block
            chance: 31
```
